//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comandamancare.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        
        public int UserID { get; set; }

        [Required(ErrorMessage = " Nume Obligatoriu ")]
        [Display(Name = "Nume de utilizator")]
        public string UserName { get; set; }

        [Required(ErrorMessage = "Parola obligatorie")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        public string LoginErrorMessage { get; set; }
    }
}
